# Template maven build

# This  template allows you to test and build your java project with maven
# The workflow allows running tests, code checkstyle and security scans on the default branch

# Prerequisities: pom.xml and appropriate project structure should exist in the repository

image: maven:3.8.3-openjdk-11

pipelines:
  default:
    - step:
        name: 'nopcommercedemo'
        caches:
          - maven
        script:
          # Install Google Chrome
          - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
          - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
          - apt-get update
          - apt-get install -y google-chrome-stable

          # Install ChromeDriver
          - CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          - wget -q https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          - unzip chromedriver_linux64.zip
          - rm chromedriver_linux64.zip
          - mv chromedriver /usr/local/bin/
          - chmod +x /usr/local/bin/chromedriver
          
          # Set up ChromeOptions
          - export CHROME_BIN=/usr/bin/google-chrome-stable
          - export DISPLAY=:99
          - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          - sleep 3
          - CHROME_OPTIONS="--no-sandbox --disable-gpu --disable-extensions --disable-dev-shm-usage"

          # Run Maven test with ChromeOptions
          - mvn clean test -Dcucumber.options="--tags @test" -Dbrowser=chrome -Dchrome.options="$CHROME_OPTIONS"
